const palette = [
    { borderColor: '#00d2ff', backgroundColor: 'rgba(0, 210, 255, 0.22)' },
    { borderColor: '#00ff88', backgroundColor: 'rgba(0, 255, 136, 0.22)' },
    { borderColor: '#ffb347', backgroundColor: 'rgba(255, 179, 71, 0.22)' },
    { borderColor: '#ff6b6b', backgroundColor: 'rgba(255, 107, 107, 0.22)' },
    { borderColor: '#b388ff', backgroundColor: 'rgba(179, 136, 255, 0.22)' },
    { borderColor: '#5eead4', backgroundColor: 'rgba(94, 234, 212, 0.22)' }
];

const monthLabels = ['Nov 2025', 'Dec 2025', 'Jan 2026', 'Feb 2026', 'Mar 2026', 'Apr 2026'];

const startupDetailsById = {
    1: {
        id: 1,
        name: 'RupeeRoute',
        sector: 'Fintech',
        fundingStage: 'Series B',
        city: 'Bengaluru',
        state: 'Karnataka',
        foundedYear: 2020,
        founders: 'Aarav Menon, Diya Rao',
        businessModel: 'UPI-led SME payments and working-capital rails',
        revenueModel: 'Take-rate on transactions plus SaaS reconciliation fees',
        description: 'Processes high-volume payments for kirana chains and D2C sellers with embedded invoice financing.',
        partnerName: 'HDFC Bank',
        dealType: 'Pilot',
        marketTrend: 84,
        competitorScore: 62,
        impactScore: 9.1,
        valuation: 3200000000,
        employeeCount: 180,
        totalFunding: 300000000,
        riskScore: 29.5,
        riskLevel: 'Low',
        cac: 3200,
        ltv: 23600,
        burnRate: 7000000,
        runway: 18.2,
        churnRate: 1.9,
        customerCount: 114000,
        history: [62000000, 68000000, 72000000, 78000000, 84000000, 89000000]
    },
    2: {
        id: 2,
        name: 'LedgerLeap',
        sector: 'Fintech',
        fundingStage: 'Series A',
        city: 'Mumbai',
        state: 'Maharashtra',
        foundedYear: 2021,
        founders: 'Kabir Sethi, Neha Batra',
        businessModel: 'Credit analytics API for NBFCs and digital lenders',
        revenueModel: 'Per-decision API fee plus platform subscription',
        description: 'Gives lenders GST, banking, and bureau-enriched underwriting signals for MSME credit.',
        partnerName: 'ICICI Bank',
        dealType: 'Pilot',
        marketTrend: 76,
        competitorScore: 58,
        impactScore: 7.9,
        valuation: 1150000000,
        employeeCount: 95,
        totalFunding: 110000000,
        riskScore: 39,
        riskLevel: 'Medium',
        cac: 4200,
        ltv: 19800,
        burnRate: 9000000,
        runway: 14.2,
        churnRate: 3.2,
        customerCount: 37000,
        history: [18000000, 20000000, 22000000, 24000000, 27000000, 30000000]
    },
    3: {
        id: 3,
        name: 'LearnNest',
        sector: 'Edtech',
        fundingStage: 'Series A',
        city: 'Gurugram',
        state: 'Haryana',
        foundedYear: 2019,
        founders: 'Rhea Malhotra, Sarthak Jain',
        businessModel: 'Hybrid K-12 test-prep platform for tier-2 cities',
        revenueModel: 'Annual learner subscriptions and school licensing',
        description: 'Combines adaptive practice, doubt-solving, and franchise learning hubs for board and entrance exams.',
        partnerName: 'Delhi Public School Network',
        dealType: 'LOI',
        marketTrend: 68,
        competitorScore: 60,
        impactScore: 8,
        valuation: 1450000000,
        employeeCount: 140,
        totalFunding: 130000000,
        riskScore: 39.5,
        riskLevel: 'Medium',
        cac: 5400,
        ltv: 16200,
        burnRate: 11000000,
        runway: 11.5,
        churnRate: 4.1,
        customerCount: 51000,
        history: [26000000, 27500000, 29500000, 31500000, 33500000, 35500000]
    },
    4: {
        id: 4,
        name: 'MediMitra',
        sector: 'Healthtech',
        fundingStage: 'Series B',
        city: 'Bengaluru',
        state: 'Karnataka',
        foundedYear: 2018,
        founders: 'Dr. Ishaan Nair, Kavya Srinivasan',
        businessModel: 'AI triage and chronic-care operating system for clinics',
        revenueModel: 'Clinic SaaS, care-plan fees, and diagnostics referral margin',
        description: 'Supports family clinics with appointment routing, risk triage, and longitudinal patient monitoring.',
        partnerName: 'Apollo Clinics',
        dealType: 'Pilot',
        marketTrend: 71,
        competitorScore: 55,
        impactScore: 8.7,
        valuation: 2400000000,
        employeeCount: 210,
        totalFunding: 240000000,
        riskScore: 46,
        riskLevel: 'Medium',
        cac: 7800,
        ltv: 24800,
        burnRate: 17000000,
        runway: 7.8,
        churnRate: 2.3,
        customerCount: 16400,
        history: [44000000, 46000000, 48000000, 50000000, 53000000, 56000000]
    },
    5: {
        id: 5,
        name: 'FleetMesh',
        sector: 'Logistics',
        fundingStage: 'Seed',
        city: 'Mumbai',
        state: 'Maharashtra',
        foundedYear: 2022,
        founders: 'Pranav Kulkarni, Sana Merchant',
        businessModel: 'Last-mile fleet orchestration for D2C and pharma deliveries',
        revenueModel: 'Per-shipment routing fee and monthly fleet dashboard subscription',
        description: 'Optimizes riders, cold-chain slots, and reverse logistics for dense urban delivery corridors.',
        partnerName: 'Blue Dart',
        dealType: 'Pilot',
        marketTrend: 59,
        competitorScore: 72,
        impactScore: 6.8,
        valuation: 520000000,
        employeeCount: 70,
        totalFunding: 43000000,
        riskScore: 73,
        riskLevel: 'High',
        cac: 6100,
        ltv: 12800,
        burnRate: 13000000,
        runway: 4.9,
        churnRate: 6.8,
        customerCount: 7200,
        history: [9000000, 10000000, 11000000, 12000000, 12500000, 13500000]
    },
    6: {
        id: 6,
        name: 'CarbonLoop',
        sector: 'ClimateTech',
        fundingStage: 'Seed',
        city: 'Pune',
        state: 'Maharashtra',
        foundedYear: 2022,
        founders: 'Mira Deshpande, Advait Roy',
        businessModel: 'Carbon accounting and supplier decarbonization workflow',
        revenueModel: 'Annual compliance SaaS and verified project marketplace fees',
        description: 'Helps mid-market exporters measure Scope 3 emissions and source lower-carbon suppliers.',
        partnerName: 'Tata Power Distribution',
        dealType: 'LOI',
        marketTrend: 74,
        competitorScore: 49,
        impactScore: 8.4,
        valuation: 480000000,
        employeeCount: 55,
        totalFunding: 52000000,
        riskScore: 56.5,
        riskLevel: 'Medium',
        cac: 3200,
        ltv: 14400,
        burnRate: 9000000,
        runway: 6.1,
        churnRate: 4.8,
        customerCount: 3900,
        history: [7000000, 8000000, 9000000, 10000000, 11500000, 12200000]
    },
    7: {
        id: 7,
        name: 'StackPilot',
        sector: 'SaaS',
        fundingStage: 'Series A',
        city: 'Bengaluru',
        state: 'Karnataka',
        foundedYear: 2020,
        founders: 'Vikram Shah, Aisha Thomas',
        businessModel: 'DevOps automation cockpit for Indian SaaS teams',
        revenueModel: 'Seat-based subscription and enterprise observability add-ons',
        description: 'Automates deployment checks, cloud-cost alerts, and release workflows for engineering teams.',
        partnerName: 'Zoho Marketplace',
        dealType: 'Pilot',
        marketTrend: 81,
        competitorScore: 57,
        impactScore: 7.6,
        valuation: 1700000000,
        employeeCount: 125,
        totalFunding: 130000000,
        riskScore: 31,
        riskLevel: 'Low',
        cac: 2800,
        ltv: 18200,
        burnRate: 7500000,
        runway: 16.7,
        churnRate: 2.1,
        customerCount: 22100,
        history: [30000000, 32000000, 35000000, 38000000, 41000000, 45000000]
    },
    8: {
        id: 8,
        name: 'AgriPulse',
        sector: 'Agritech',
        fundingStage: 'Seed',
        city: 'Nashik',
        state: 'Maharashtra',
        foundedYear: 2021,
        founders: 'Harsh Patil, Nandini Verma',
        businessModel: 'Farm advisory, mandi pricing, and input-credit workflow',
        revenueModel: 'Input marketplace margin and FPO subscription',
        description: 'Connects grape, onion, and tomato FPOs to crop intelligence, working capital, and buyer discovery.',
        partnerName: 'Mahindra Agri Solutions',
        dealType: 'LOI',
        marketTrend: 66,
        competitorScore: 53,
        impactScore: 7.7,
        valuation: 390000000,
        employeeCount: 48,
        totalFunding: 36000000,
        riskScore: 52,
        riskLevel: 'Medium',
        cac: 1900,
        ltv: 9300,
        burnRate: 5200000,
        runway: 8.8,
        churnRate: 5.2,
        customerCount: 18200,
        history: [6200000, 7100000, 7900000, 8600000, 9400000, 10800000]
    },
    9: {
        id: 9,
        name: 'SecureAuth',
        sector: 'Cybersecurity',
        fundingStage: 'Series A',
        city: 'Hyderabad',
        state: 'Telangana',
        foundedYear: 2020,
        founders: 'Nikhil Reddy, Samira Khan',
        businessModel: 'Passwordless identity layer for regulated enterprises',
        revenueModel: 'Annual contract value by active workforce identities',
        description: 'Delivers phishing-resistant authentication for banks, insurers, and healthcare administrators.',
        partnerName: 'NPCI Partner Program',
        dealType: 'Pilot',
        marketTrend: 79,
        competitorScore: 48,
        impactScore: 8.2,
        valuation: 920000000,
        employeeCount: 88,
        totalFunding: 95000000,
        riskScore: 34,
        riskLevel: 'Low',
        cac: 7600,
        ltv: 45200,
        burnRate: 8200000,
        runway: 13.4,
        churnRate: 1.6,
        customerCount: 860,
        history: [11500000, 13200000, 15400000, 17200000, 19800000, 23000000]
    },
    10: {
        id: 10,
        name: 'BazaarBridge',
        sector: 'Ecommerce',
        fundingStage: 'Seed',
        city: 'Jaipur',
        state: 'Rajasthan',
        foundedYear: 2022,
        founders: 'Tanvi Agarwal, Dhruv Mehta',
        businessModel: 'B2B catalog and fulfillment network for small retailers',
        revenueModel: 'Marketplace margin, logistics fee, and promoted catalog slots',
        description: 'Lets small fashion and home-goods retailers source inventory from verified Indian manufacturers.',
        partnerName: 'IndiaMART Seller Network',
        dealType: 'LOI',
        marketTrend: 63,
        competitorScore: 68,
        impactScore: 6.9,
        valuation: 610000000,
        employeeCount: 82,
        totalFunding: 58000000,
        riskScore: 62,
        riskLevel: 'Medium',
        cac: 2600,
        ltv: 9800,
        burnRate: 9600000,
        runway: 5.7,
        churnRate: 7.1,
        customerCount: 24800,
        history: [10500000, 11800000, 12900000, 14100000, 15400000, 16800000]
    },
    11: {
        id: 11,
        name: 'InsureVista',
        sector: 'Insurtech',
        fundingStage: 'Series A',
        city: 'Mumbai',
        state: 'Maharashtra',
        foundedYear: 2020,
        founders: 'Yash Gupta, Meera Iyer',
        businessModel: 'Embedded insurance APIs for travel, lending, and ecommerce',
        revenueModel: 'Policy commission and API platform fee',
        description: 'Bundles contextual insurance into digital checkout flows with automated claims routing.',
        partnerName: 'Bajaj Allianz',
        dealType: 'Pilot',
        marketTrend: 72,
        competitorScore: 54,
        impactScore: 8,
        valuation: 1040000000,
        employeeCount: 104,
        totalFunding: 118000000,
        riskScore: 37,
        riskLevel: 'Medium',
        cac: 3900,
        ltv: 21000,
        burnRate: 8700000,
        runway: 12.6,
        churnRate: 2.8,
        customerCount: 42000,
        history: [17800000, 19300000, 21100000, 23500000, 25900000, 28700000]
    },
    12: {
        id: 12,
        name: 'PayKart',
        sector: 'Fintech',
        fundingStage: 'Seed',
        city: 'Chennai',
        state: 'Tamil Nadu',
        foundedYear: 2023,
        founders: 'Arjun Krishnan, Lavanya Moorthy',
        businessModel: 'Offline merchant QR loyalty and micro-credit enablement',
        revenueModel: 'Merchant SaaS plus referral margin on credit products',
        description: 'Gives neighbourhood merchants a lightweight rewards stack tied to UPI payments and credit offers.',
        partnerName: 'Federal Bank',
        dealType: 'LOI',
        marketTrend: 70,
        competitorScore: 64,
        impactScore: 7.2,
        valuation: 430000000,
        employeeCount: 42,
        totalFunding: 41000000,
        riskScore: 58,
        riskLevel: 'Medium',
        cac: 1700,
        ltv: 7600,
        burnRate: 6100000,
        runway: 7.2,
        churnRate: 5.9,
        customerCount: 53000,
        history: [5200000, 6400000, 7800000, 9100000, 10400000, 12100000]
    },
    13: {
        id: 13,
        name: 'DroneKart',
        sector: 'Dronetech',
        fundingStage: 'Series A',
        city: 'Noida',
        state: 'Uttar Pradesh',
        foundedYear: 2021,
        founders: 'Raghav Bansal, Pari Saxena',
        businessModel: 'Drone-as-a-service for surveying, agri spraying, and inspections',
        revenueModel: 'Per-acre and per-site service revenue with maintenance contracts',
        description: 'Operates certified drone fleets for agri cooperatives, solar farms, and infrastructure teams.',
        partnerName: 'Adani Green Field Ops',
        dealType: 'Pilot',
        marketTrend: 69,
        competitorScore: 59,
        impactScore: 7.8,
        valuation: 760000000,
        employeeCount: 118,
        totalFunding: 88000000,
        riskScore: 49,
        riskLevel: 'Medium',
        cac: 9400,
        ltv: 31200,
        burnRate: 11800000,
        runway: 8.1,
        churnRate: 3.6,
        customerCount: 1320,
        history: [12800000, 14200000, 15800000, 17600000, 19600000, 21900000]
    },
    14: {
        id: 14,
        name: 'BioBloom',
        sector: 'Biotech',
        fundingStage: 'Seed',
        city: 'Hyderabad',
        state: 'Telangana',
        foundedYear: 2022,
        founders: 'Dr. Ananya Bose, Kunal Narang',
        businessModel: 'Synthetic biology workflow for enzyme discovery',
        revenueModel: 'Research contracts, IP licensing, and pilot manufacturing margin',
        description: 'Uses rapid wet-lab automation to build enzymes for specialty chemicals and food processing.',
        partnerName: 'CCMB Incubator',
        dealType: 'LOI',
        marketTrend: 62,
        competitorScore: 46,
        impactScore: 7.4,
        valuation: 580000000,
        employeeCount: 64,
        totalFunding: 64000000,
        riskScore: 67,
        riskLevel: 'High',
        cac: 18500,
        ltv: 54500,
        burnRate: 14200000,
        runway: 5.2,
        churnRate: 4.4,
        customerCount: 34,
        history: [4200000, 4900000, 5600000, 6600000, 7500000, 8900000]
    },
    15: {
        id: 15,
        name: 'SkillSprint',
        sector: 'Edtech',
        fundingStage: 'Seed',
        city: 'Bengaluru',
        state: 'Karnataka',
        foundedYear: 2023,
        founders: 'Pooja Kamat, Ishan Grover',
        businessModel: 'Outcome-linked skilling for entry-level tech and operations roles',
        revenueModel: 'Placement success fee and employer cohort sponsorship',
        description: 'Runs short-form job tracks for support, data ops, and QA roles with placement-linked pricing.',
        partnerName: 'NASSCOM FutureSkills',
        dealType: 'Pilot',
        marketTrend: 65,
        competitorScore: 61,
        impactScore: 7.5,
        valuation: 350000000,
        employeeCount: 38,
        totalFunding: 30000000,
        riskScore: 51,
        riskLevel: 'Medium',
        cac: 2100,
        ltv: 8200,
        burnRate: 4300000,
        runway: 9.3,
        churnRate: 5.5,
        customerCount: 16400,
        history: [3900000, 4700000, 5600000, 6800000, 7900000, 9100000]
    },
    16: {
        id: 16,
        name: 'Warewise',
        sector: 'Logistics',
        fundingStage: 'Series A',
        city: 'Delhi',
        state: 'Delhi',
        foundedYear: 2020,
        founders: 'Anmol Dua, Kritika Suri',
        businessModel: 'Warehouse intelligence and demand allocation for brands',
        revenueModel: 'Warehouse SaaS plus per-order optimization fee',
        description: 'Uses inventory velocity and demand forecasts to allocate stock across metro warehouses.',
        partnerName: 'Delhivery Fulfillment',
        dealType: 'Pilot',
        marketTrend: 73,
        competitorScore: 56,
        impactScore: 8.1,
        valuation: 980000000,
        employeeCount: 112,
        totalFunding: 104000000,
        riskScore: 41,
        riskLevel: 'Medium',
        cac: 5200,
        ltv: 24800,
        burnRate: 7600000,
        runway: 12.1,
        churnRate: 2.9,
        customerCount: 6700,
        history: [15000000, 16600000, 18300000, 20500000, 22800000, 25700000]
    },
    17: {
        id: 17,
        name: 'GreenGrid',
        sector: 'Energy',
        fundingStage: 'Series B',
        city: 'Ahmedabad',
        state: 'Gujarat',
        foundedYear: 2019,
        founders: 'Jay Shah, Riddhi Trivedi',
        businessModel: 'Battery analytics and demand response for C&I solar users',
        revenueModel: 'Energy savings share and equipment analytics subscription',
        description: 'Optimizes battery dispatch and peak shaving for commercial solar-plus-storage installations.',
        partnerName: 'Torrent Power',
        dealType: 'Pilot',
        marketTrend: 77,
        competitorScore: 51,
        impactScore: 8.6,
        valuation: 2100000000,
        employeeCount: 176,
        totalFunding: 220000000,
        riskScore: 35,
        riskLevel: 'Low',
        cac: 11800,
        ltv: 61800,
        burnRate: 15300000,
        runway: 15.5,
        churnRate: 1.8,
        customerCount: 720,
        history: [33500000, 35800000, 38400000, 42000000, 46100000, 50500000]
    },
    18: {
        id: 18,
        name: 'CloudKirana',
        sector: 'SaaS',
        fundingStage: 'Seed',
        city: 'Gurugram',
        state: 'Haryana',
        foundedYear: 2023,
        founders: 'Rohan Kapoor, Zoya Siddiqui',
        businessModel: 'Retail operating system for kirana procurement and ledgering',
        revenueModel: 'Store subscription and supplier promotion revenue',
        description: 'Gives small retailers procurement lists, digital ledgers, expiry alerts, and margin analytics.',
        partnerName: 'Metro Cash & Carry',
        dealType: 'LOI',
        marketTrend: 75,
        competitorScore: 60,
        impactScore: 7.3,
        valuation: 470000000,
        employeeCount: 46,
        totalFunding: 39000000,
        riskScore: 54,
        riskLevel: 'Medium',
        cac: 1500,
        ltv: 7900,
        burnRate: 5000000,
        runway: 8.4,
        churnRate: 6.1,
        customerCount: 31500,
        history: [4800000, 5900000, 7100000, 8300000, 9700000, 11200000]
    }
};

const additionalStartupBlueprints = [
    {
        id: 19,
        name: 'FarmLinker',
        sector: 'Agritech',
        fundingStage: 'Series A',
        city: 'Lucknow',
        state: 'Uttar Pradesh',
        foundingYear: 2021,
        founders: 'Ankit Tiwari, Sara Khan',
        businessModel: 'FPO procurement, crop advisory, and harvest financing network',
        revenueModel: 'Input margin, buyer commission, and working-capital referral fees',
        description: 'Connects wheat, pulse, and vegetable FPOs with verified buyers, agronomy support, and embedded credit.',
        partnerName: 'IFFCO Kisan',
        dealType: 'Pilot',
        marketTrend: 72,
        competitorScore: 52,
        impactScore: 7.8,
        valuationCr: 82,
        fundingCr: 9.5,
        employeeCount: 76,
        riskScore: 44,
        cac: 2300,
        ltv: 11800,
        burnRateCr: 0.62,
        runway: 10.8,
        churnRate: 4.6,
        customerCount: 28600,
        monthlyRevenueCr: 2.1
    },
    {
        id: 20,
        name: 'CreditSutra',
        sector: 'Fintech',
        fundingStage: 'Series A',
        city: 'Ahmedabad',
        state: 'Gujarat',
        foundingYear: 2020,
        founders: 'Mihir Shah, Nupur Desai',
        businessModel: 'Cash-flow underwriting for retailers and micro-distributors',
        revenueModel: 'Loan origination fee, risk analytics SaaS, and collection success fee',
        description: 'Underwrites small merchants using GST, UPI, and distributor-ledger signals for short-tenure credit.',
        partnerName: 'Axis Bank',
        dealType: 'Pilot',
        marketTrend: 78,
        competitorScore: 61,
        impactScore: 8.2,
        valuationCr: 136,
        fundingCr: 14,
        employeeCount: 104,
        riskScore: 38,
        cac: 3600,
        ltv: 20700,
        burnRateCr: 0.82,
        runway: 14.9,
        churnRate: 2.9,
        customerCount: 46000,
        monthlyRevenueCr: 3.4
    },
    {
        id: 21,
        name: 'TutorHive',
        sector: 'Edtech',
        fundingStage: 'Seed',
        city: 'Pune',
        state: 'Maharashtra',
        foundingYear: 2022,
        founders: 'Kriti Mehta, Omar Shaikh',
        businessModel: 'Live small-group tutoring for competitive exams and school bridge courses',
        revenueModel: 'Monthly cohort subscriptions and teacher marketplace commission',
        description: 'Runs live mentor pods for NEET, JEE foundation, and board preparation in tier-2 cities.',
        partnerName: 'Allen Career Partner Network',
        dealType: 'LOI',
        marketTrend: 64,
        competitorScore: 66,
        impactScore: 7.1,
        valuationCr: 44,
        fundingCr: 4.8,
        employeeCount: 42,
        riskScore: 57,
        cac: 2900,
        ltv: 10400,
        burnRateCr: 0.41,
        runway: 8.2,
        churnRate: 5.8,
        customerCount: 14200,
        monthlyRevenueCr: 0.92
    },
    {
        id: 22,
        name: 'MedGenomeX',
        sector: 'Biotech',
        fundingStage: 'Series A',
        city: 'Bengaluru',
        state: 'Karnataka',
        foundingYear: 2019,
        founders: 'Dr. Radhika Sen, Manav Rao',
        businessModel: 'Clinical genomics decision support for oncology and rare-disease labs',
        revenueModel: 'Test interpretation fees, hospital SaaS, and research partnership revenue',
        description: 'Combines genetic reports, variant interpretation, and clinician workflows for advanced diagnostics.',
        partnerName: 'Narayana Health Labs',
        dealType: 'Pilot',
        marketTrend: 70,
        competitorScore: 47,
        impactScore: 8.5,
        valuationCr: 168,
        fundingCr: 18,
        employeeCount: 132,
        riskScore: 48,
        cac: 14500,
        ltv: 52600,
        burnRateCr: 1.28,
        runway: 9.6,
        churnRate: 3.4,
        customerCount: 420,
        monthlyRevenueCr: 2.7
    },
    {
        id: 23,
        name: 'CityCharge',
        sector: 'Mobility',
        fundingStage: 'Seed',
        city: 'Delhi',
        state: 'Delhi',
        foundingYear: 2022,
        founders: 'Rajat Bedi, Simran Kaur',
        businessModel: 'EV charging discovery and fleet energy management for urban operators',
        revenueModel: 'Charging transaction fee and fleet dashboard subscription',
        description: 'Aggregates charging points and helps delivery fleets plan routes, payments, and uptime.',
        partnerName: 'Tata Power EV Charging',
        dealType: 'LOI',
        marketTrend: 80,
        competitorScore: 58,
        impactScore: 8.1,
        valuationCr: 68,
        fundingCr: 7.2,
        employeeCount: 58,
        riskScore: 53,
        cac: 3100,
        ltv: 14200,
        burnRateCr: 0.74,
        runway: 7.4,
        churnRate: 4.9,
        customerCount: 9400,
        monthlyRevenueCr: 1.18
    },
    {
        id: 24,
        name: 'SolarSetu',
        sector: 'Energy',
        fundingStage: 'Series A',
        city: 'Jaipur',
        state: 'Rajasthan',
        foundingYear: 2020,
        founders: 'Devansh Agarwal, Mitali Soni',
        businessModel: 'Solar project monitoring and financing workflow for MSME rooftops',
        revenueModel: 'Project success fee, monitoring SaaS, and lender referral margin',
        description: 'Digitizes rooftop solar proposals, installer QA, energy analytics, and repayment tracking.',
        partnerName: 'Rajasthan Renewable Energy Corp',
        dealType: 'Pilot',
        marketTrend: 79,
        competitorScore: 50,
        impactScore: 8.3,
        valuationCr: 150,
        fundingCr: 16,
        employeeCount: 116,
        riskScore: 36,
        cac: 8200,
        ltv: 44800,
        burnRateCr: 0.92,
        runway: 16.1,
        churnRate: 1.9,
        customerCount: 1650,
        monthlyRevenueCr: 4.2
    },
    {
        id: 25,
        name: 'HireOrbit',
        sector: 'HRTech',
        fundingStage: 'Seed',
        city: 'Noida',
        state: 'Uttar Pradesh',
        foundingYear: 2023,
        founders: 'Naina Kapoor, Harit Bansal',
        businessModel: 'Skill graph based hiring for early career roles',
        revenueModel: 'Employer subscription, assessment fees, and success-based placement revenue',
        description: 'Matches candidates to entry-level tech, support, and operations roles using verified skill evidence.',
        partnerName: 'TeamLease Digital',
        dealType: 'Pilot',
        marketTrend: 73,
        competitorScore: 59,
        impactScore: 7.4,
        valuationCr: 39,
        fundingCr: 3.6,
        employeeCount: 34,
        riskScore: 50,
        cac: 1800,
        ltv: 9900,
        burnRateCr: 0.34,
        runway: 9.7,
        churnRate: 4.2,
        customerCount: 18800,
        monthlyRevenueCr: 0.84
    },
    {
        id: 26,
        name: 'LegalMind',
        sector: 'LegalTech',
        fundingStage: 'Seed',
        city: 'Bengaluru',
        state: 'Karnataka',
        foundingYear: 2022,
        founders: 'Rishabh Jain, Alisha Dsouza',
        businessModel: 'Contract intelligence and compliance workflow for mid-market companies',
        revenueModel: 'Seat-based SaaS and document automation usage fees',
        description: 'Automates contract review, obligation tracking, and legal-risk triage for finance and HR teams.',
        partnerName: 'Cyril Amarchand Innovation Lab',
        dealType: 'LOI',
        marketTrend: 71,
        competitorScore: 54,
        impactScore: 7.9,
        valuationCr: 52,
        fundingCr: 5.1,
        employeeCount: 44,
        riskScore: 43,
        cac: 4200,
        ltv: 22800,
        burnRateCr: 0.48,
        runway: 11.3,
        churnRate: 2.7,
        customerCount: 610,
        monthlyRevenueCr: 1.05
    },
    {
        id: 27,
        name: 'HomeHarbor',
        sector: 'Proptech',
        fundingStage: 'Series A',
        city: 'Mumbai',
        state: 'Maharashtra',
        foundingYear: 2020,
        founders: 'Vivaan Dutt, Sana Qureshi',
        businessModel: 'Rental underwriting and managed-home workflow for urban landlords',
        revenueModel: 'Managed rent fee, tenant verification fee, and property SaaS subscription',
        description: 'Combines tenant risk scoring, rent collection, and maintenance coordination for small landlords.',
        partnerName: 'Godrej Properties Channel Partner',
        dealType: 'Pilot',
        marketTrend: 69,
        competitorScore: 63,
        impactScore: 7.2,
        valuationCr: 118,
        fundingCr: 12,
        employeeCount: 92,
        riskScore: 47,
        cac: 5100,
        ltv: 21800,
        burnRateCr: 0.88,
        runway: 10.6,
        churnRate: 3.8,
        customerCount: 7600,
        monthlyRevenueCr: 2.8
    },
    {
        id: 28,
        name: 'FoodSaathi',
        sector: 'Foodtech',
        fundingStage: 'Seed',
        city: 'Hyderabad',
        state: 'Telangana',
        foundingYear: 2022,
        founders: 'Prisha Reddy, Adil Hussain',
        businessModel: 'Cloud kitchen procurement and demand forecasting for regional food brands',
        revenueModel: 'Procurement margin, SaaS subscription, and packaging marketplace fees',
        description: 'Helps small food brands forecast demand, buy ingredients, and manage delivery-channel margins.',
        partnerName: 'Swiggy Minis Partner Program',
        dealType: 'LOI',
        marketTrend: 67,
        competitorScore: 70,
        impactScore: 6.9,
        valuationCr: 36,
        fundingCr: 3.8,
        employeeCount: 40,
        riskScore: 61,
        cac: 2400,
        ltv: 8600,
        burnRateCr: 0.52,
        runway: 6.2,
        churnRate: 7.5,
        customerCount: 12500,
        monthlyRevenueCr: 0.98
    },
    {
        id: 29,
        name: 'GameGrid',
        sector: 'Gaming',
        fundingStage: 'Seed',
        city: 'Pune',
        state: 'Maharashtra',
        foundingYear: 2023,
        founders: 'Abeer Kulkarni, Mehak Arora',
        businessModel: 'Casual mobile games with vernacular tournaments and creator events',
        revenueModel: 'In-app purchases, brand sponsorships, and tournament entry fees',
        description: 'Builds lightweight Indian-language games with local creator-led competitions.',
        partnerName: 'JioGames',
        dealType: 'Pilot',
        marketTrend: 76,
        competitorScore: 73,
        impactScore: 7,
        valuationCr: 58,
        fundingCr: 6,
        employeeCount: 51,
        riskScore: 59,
        cac: 900,
        ltv: 3400,
        burnRateCr: 0.57,
        runway: 8,
        churnRate: 8.4,
        customerCount: 280000,
        monthlyRevenueCr: 1.22
    },
    {
        id: 30,
        name: 'VaaniAI',
        sector: 'AI/ML',
        fundingStage: 'Series A',
        city: 'Chennai',
        state: 'Tamil Nadu',
        foundingYear: 2021,
        founders: 'Sridhar Raman, Farah Ansari',
        businessModel: 'Voice AI agents for Indian customer support and collections teams',
        revenueModel: 'Usage-based AI minutes and enterprise platform subscription',
        description: 'Automates multilingual support calls, repayment reminders, and intent routing for Indian enterprises.',
        partnerName: 'Freshworks Marketplace',
        dealType: 'Pilot',
        marketTrend: 86,
        competitorScore: 57,
        impactScore: 8.5,
        valuationCr: 190,
        fundingCr: 20,
        employeeCount: 128,
        riskScore: 32,
        cac: 6200,
        ltv: 39200,
        burnRateCr: 1.18,
        runway: 15.8,
        churnRate: 1.8,
        customerCount: 1400,
        monthlyRevenueCr: 5.1
    },
    {
        id: 31,
        name: 'SpaceKart',
        sector: 'SpaceTech',
        fundingStage: 'Series A',
        city: 'Ahmedabad',
        state: 'Gujarat',
        foundingYear: 2020,
        founders: 'Yuvan Mehta, Dr. Ira Nair',
        businessModel: 'Satellite imagery workflow for agriculture, insurance, and infrastructure monitoring',
        revenueModel: 'Imagery API usage, enterprise dashboards, and analytics contracts',
        description: 'Converts satellite and geospatial data into crop, asset, and climate-risk intelligence.',
        partnerName: 'ISRO IN-SPACe Incubation',
        dealType: 'LOI',
        marketTrend: 82,
        competitorScore: 44,
        impactScore: 8.6,
        valuationCr: 210,
        fundingCr: 22,
        employeeCount: 142,
        riskScore: 41,
        cac: 13200,
        ltv: 68200,
        burnRateCr: 1.42,
        runway: 13.2,
        churnRate: 2.4,
        customerCount: 320,
        monthlyRevenueCr: 3.6
    },
    {
        id: 32,
        name: 'RoboWorks',
        sector: 'Robotics',
        fundingStage: 'Seed',
        city: 'Coimbatore',
        state: 'Tamil Nadu',
        foundingYear: 2022,
        founders: 'Arvind Subramaniam, Kavita Menon',
        businessModel: 'Warehouse picking robots and deployment software for mid-sized facilities',
        revenueModel: 'Robot leasing, maintenance contract, and orchestration SaaS',
        description: 'Builds modular robots for repetitive warehouse picking, sorting, and line-feeding workflows.',
        partnerName: 'TVS Supply Chain',
        dealType: 'Pilot',
        marketTrend: 74,
        competitorScore: 55,
        impactScore: 8.1,
        valuationCr: 76,
        fundingCr: 8,
        employeeCount: 68,
        riskScore: 56,
        cac: 14800,
        ltv: 50600,
        burnRateCr: 0.96,
        runway: 7.9,
        churnRate: 3.1,
        customerCount: 84,
        monthlyRevenueCr: 1.04
    },
    {
        id: 33,
        name: 'SupplySense',
        sector: 'Logistics',
        fundingStage: 'Series A',
        city: 'Kolkata',
        state: 'West Bengal',
        foundingYear: 2020,
        founders: 'Anirban Ghosh, Tia Basu',
        businessModel: 'Supply-chain control tower for eastern India distributors',
        revenueModel: 'Per-shipment visibility fee and control-tower subscription',
        description: 'Gives brands ETA prediction, vendor scorecards, and exception workflows across rail-road lanes.',
        partnerName: 'TCI Express',
        dealType: 'Pilot',
        marketTrend: 71,
        competitorScore: 58,
        impactScore: 7.6,
        valuationCr: 104,
        fundingCr: 11,
        employeeCount: 92,
        riskScore: 45,
        cac: 5200,
        ltv: 23800,
        burnRateCr: 0.75,
        runway: 12.4,
        churnRate: 3.3,
        customerCount: 5800,
        monthlyRevenueCr: 2.55
    },
    {
        id: 34,
        name: 'TrustVault',
        sector: 'Cybersecurity',
        fundingStage: 'Series B',
        city: 'Gurugram',
        state: 'Haryana',
        foundingYear: 2019,
        founders: 'Kabir Anand, Rukmini Paul',
        businessModel: 'Zero-trust data access and audit trails for regulated companies',
        revenueModel: 'Annual enterprise contracts and compliance reporting add-ons',
        description: 'Secures employee, vendor, and API access for banks, insurers, and large healthcare networks.',
        partnerName: 'Microsoft for Startups',
        dealType: 'Pilot',
        marketTrend: 84,
        competitorScore: 49,
        impactScore: 8.8,
        valuationCr: 260,
        fundingCr: 28,
        employeeCount: 168,
        riskScore: 28,
        cac: 9200,
        ltv: 61200,
        burnRateCr: 1.05,
        runway: 18.9,
        churnRate: 1.4,
        customerCount: 540,
        monthlyRevenueCr: 7.2
    },
    {
        id: 35,
        name: 'D2CFlow',
        sector: 'Ecommerce',
        fundingStage: 'Series A',
        city: 'Bengaluru',
        state: 'Karnataka',
        foundingYear: 2021,
        founders: 'Nisha Rao, Karan Malhotra',
        businessModel: 'Commerce operating system for D2C brands',
        revenueModel: 'Subscription, logistics margin, and marketing automation usage fees',
        description: 'Unifies storefront, fulfillment, return intelligence, and retention campaigns for fast-growing brands.',
        partnerName: 'Shiprocket Partner Network',
        dealType: 'Pilot',
        marketTrend: 77,
        competitorScore: 62,
        impactScore: 7.7,
        valuationCr: 126,
        fundingCr: 13,
        employeeCount: 98,
        riskScore: 42,
        cac: 3100,
        ltv: 15600,
        burnRateCr: 0.86,
        runway: 12.8,
        churnRate: 4.1,
        customerCount: 19800,
        monthlyRevenueCr: 3.1
    },
    {
        id: 36,
        name: 'PolicyPulse',
        sector: 'Insurtech',
        fundingStage: 'Seed',
        city: 'Mumbai',
        state: 'Maharashtra',
        foundingYear: 2022,
        founders: 'Ameya Joshi, Isha Fernandes',
        businessModel: 'SME insurance advisory and renewal intelligence platform',
        revenueModel: 'Policy commission, renewal success fee, and advisory subscription',
        description: 'Helps SMEs compare cyber, liability, health, and asset policies with renewal risk alerts.',
        partnerName: 'HDFC ERGO',
        dealType: 'LOI',
        marketTrend: 69,
        competitorScore: 51,
        impactScore: 7.5,
        valuationCr: 42,
        fundingCr: 4.2,
        employeeCount: 36,
        riskScore: 46,
        cac: 2800,
        ltv: 14600,
        burnRateCr: 0.38,
        runway: 10.2,
        churnRate: 3.5,
        customerCount: 9200,
        monthlyRevenueCr: 0.9
    },
    {
        id: 37,
        name: 'CloudDesk',
        sector: 'SaaS',
        fundingStage: 'Series A',
        city: 'Chennai',
        state: 'Tamil Nadu',
        foundingYear: 2020,
        founders: 'Arjun Narayanan, Pooja Menon',
        businessModel: 'IT service desk and asset workflow for mid-market companies',
        revenueModel: 'Per-seat subscription and workflow automation add-ons',
        description: 'Manages employee devices, tickets, software assets, and internal approvals for IT teams.',
        partnerName: 'Freshservice Marketplace',
        dealType: 'Pilot',
        marketTrend: 75,
        competitorScore: 56,
        impactScore: 7.8,
        valuationCr: 142,
        fundingCr: 14.5,
        employeeCount: 112,
        riskScore: 34,
        cac: 2700,
        ltv: 17800,
        burnRateCr: 0.68,
        runway: 17.4,
        churnRate: 2.2,
        customerCount: 15600,
        monthlyRevenueCr: 3.8
    },
    {
        id: 38,
        name: 'WasteWise',
        sector: 'ClimateTech',
        fundingStage: 'Seed',
        city: 'Indore',
        state: 'Madhya Pradesh',
        foundingYear: 2022,
        founders: 'Gaurav Jain, Palak Sethi',
        businessModel: 'Waste segregation analytics and recycling marketplace for municipalities',
        revenueModel: 'Municipal SaaS, recycler marketplace margin, and compliance reporting fees',
        description: 'Digitizes wet-dry waste flows, route quality, recycler matching, and landfill diversion metrics.',
        partnerName: 'Indore Municipal Corporation',
        dealType: 'Pilot',
        marketTrend: 73,
        competitorScore: 48,
        impactScore: 8.2,
        valuationCr: 46,
        fundingCr: 4.9,
        employeeCount: 48,
        riskScore: 52,
        cac: 3900,
        ltv: 17400,
        burnRateCr: 0.46,
        runway: 8.7,
        churnRate: 4.7,
        customerCount: 1260,
        monthlyRevenueCr: 0.86
    },
    {
        id: 39,
        name: 'DroneField',
        sector: 'Dronetech',
        fundingStage: 'Seed',
        city: 'Nagpur',
        state: 'Maharashtra',
        foundingYear: 2023,
        founders: 'Sahil Wankhede, Meera Prasad',
        businessModel: 'Drone spraying and crop scouting for cotton and soybean farms',
        revenueModel: 'Per-acre service revenue and seasonal subscription for farm cooperatives',
        description: 'Operates drone fleets for crop spraying, pest detection, and field-mapping in central India.',
        partnerName: 'Krishi Vigyan Kendra Nagpur',
        dealType: 'LOI',
        marketTrend: 68,
        competitorScore: 60,
        impactScore: 7.1,
        valuationCr: 34,
        fundingCr: 3.2,
        employeeCount: 38,
        riskScore: 60,
        cac: 6200,
        ltv: 18800,
        burnRateCr: 0.44,
        runway: 6.8,
        churnRate: 5.3,
        customerCount: 980,
        monthlyRevenueCr: 0.68
    },
    {
        id: 40,
        name: 'PharmaLink',
        sector: 'Healthtech',
        fundingStage: 'Series A',
        city: 'Hyderabad',
        state: 'Telangana',
        foundingYear: 2020,
        founders: 'Dr. Sameer Ali, Tanvi Rao',
        businessModel: 'Pharmacy supply-chain visibility and cold-chain exception management',
        revenueModel: 'Distributor SaaS and per-shipment exception monitoring fee',
        description: 'Tracks medicine inventory, expiry risk, and cold-chain alerts for pharmacy distributors.',
        partnerName: 'Apollo Pharmacy',
        dealType: 'Pilot',
        marketTrend: 76,
        competitorScore: 54,
        impactScore: 8.1,
        valuationCr: 122,
        fundingCr: 12.8,
        employeeCount: 96,
        riskScore: 40,
        cac: 5600,
        ltv: 26300,
        burnRateCr: 0.78,
        runway: 13.6,
        churnRate: 2.6,
        customerCount: 6200,
        monthlyRevenueCr: 2.9
    },
    {
        id: 41,
        name: 'BharatLedger',
        sector: 'Fintech',
        fundingStage: 'Seed',
        city: 'Surat',
        state: 'Gujarat',
        foundingYear: 2023,
        founders: 'Jignesh Patel, Rhea Kapoor',
        businessModel: 'Digital ledger, payment reminders, and invoice discounting for textile traders',
        revenueModel: 'Merchant subscription, payment link fee, and financing referral margin',
        description: 'Digitizes receivables for textile MSMEs and creates working-capital signals from ledger behavior.',
        partnerName: 'Bank of Baroda MSME Cell',
        dealType: 'LOI',
        marketTrend: 74,
        competitorScore: 64,
        impactScore: 7.4,
        valuationCr: 48,
        fundingCr: 4.5,
        employeeCount: 40,
        riskScore: 55,
        cac: 1250,
        ltv: 6900,
        burnRateCr: 0.4,
        runway: 8.6,
        churnRate: 5.1,
        customerCount: 54000,
        monthlyRevenueCr: 0.96
    },
    {
        id: 42,
        name: 'LearnLoop',
        sector: 'Edtech',
        fundingStage: 'Seed',
        city: 'Jaipur',
        state: 'Rajasthan',
        foundingYear: 2022,
        founders: 'Ira Sharma, Manas Jain',
        businessModel: 'Teacher productivity and parent communication SaaS for affordable schools',
        revenueModel: 'School subscription and digital content marketplace revenue',
        description: 'Helps affordable private schools manage assignments, fees, parent updates, and learning analytics.',
        partnerName: 'Rajasthan Private Schools Association',
        dealType: 'Pilot',
        marketTrend: 66,
        competitorScore: 57,
        impactScore: 7.6,
        valuationCr: 40,
        fundingCr: 3.9,
        employeeCount: 36,
        riskScore: 49,
        cac: 1900,
        ltv: 9800,
        burnRateCr: 0.36,
        runway: 9.4,
        churnRate: 4.8,
        customerCount: 11800,
        monthlyRevenueCr: 0.82
    },
    {
        id: 43,
        name: 'BioTrace',
        sector: 'Biotech',
        fundingStage: 'Seed',
        city: 'Pune',
        state: 'Maharashtra',
        foundingYear: 2022,
        founders: 'Dr. Manya Kulkarni, Rehan Sheikh',
        businessModel: 'Lab sample traceability and compliance workflow for diagnostic chains',
        revenueModel: 'Lab SaaS, barcode workflow licensing, and integration services',
        description: 'Tracks biological samples from pickup to reporting with audit trails and compliance checks.',
        partnerName: 'Thyrocare Integration Lab',
        dealType: 'LOI',
        marketTrend: 65,
        competitorScore: 50,
        impactScore: 7.7,
        valuationCr: 55,
        fundingCr: 5.6,
        employeeCount: 52,
        riskScore: 58,
        cac: 7600,
        ltv: 24600,
        burnRateCr: 0.71,
        runway: 7.1,
        churnRate: 4,
        customerCount: 540,
        monthlyRevenueCr: 0.95
    },
    {
        id: 44,
        name: 'EVFleet',
        sector: 'Mobility',
        fundingStage: 'Series A',
        city: 'Bengaluru',
        state: 'Karnataka',
        foundingYear: 2020,
        founders: 'Nikhil Prabhu, Ayesha Thomas',
        businessModel: 'EV fleet leasing and battery-health analytics for delivery operators',
        revenueModel: 'Vehicle lease spread, maintenance fee, and analytics subscription',
        description: 'Leases two-wheeler EV fleets and predicts battery health, downtime, and route economics.',
        partnerName: 'Ather Energy Fleet Program',
        dealType: 'Pilot',
        marketTrend: 83,
        competitorScore: 59,
        impactScore: 8.4,
        valuationCr: 178,
        fundingCr: 18.5,
        employeeCount: 138,
        riskScore: 39,
        cac: 10800,
        ltv: 57800,
        burnRateCr: 1.25,
        runway: 14.5,
        churnRate: 2.5,
        customerCount: 2100,
        monthlyRevenueCr: 4.6
    },
    {
        id: 45,
        name: 'GridMitra',
        sector: 'Energy',
        fundingStage: 'Seed',
        city: 'Kochi',
        state: 'Kerala',
        foundingYear: 2022,
        founders: 'Akhil Menon, Nandita Pillai',
        businessModel: 'Smart-meter analytics and demand response for apartment communities',
        revenueModel: 'Energy savings share and community analytics subscription',
        description: 'Predicts peak load, appliance anomalies, and tariff savings for residential energy communities.',
        partnerName: 'KSEB Innovation Cell',
        dealType: 'LOI',
        marketTrend: 72,
        competitorScore: 45,
        impactScore: 7.9,
        valuationCr: 49,
        fundingCr: 5.2,
        employeeCount: 43,
        riskScore: 46,
        cac: 4600,
        ltv: 22800,
        burnRateCr: 0.42,
        runway: 11.1,
        churnRate: 2.9,
        customerCount: 8400,
        monthlyRevenueCr: 0.88
    },
    {
        id: 46,
        name: 'PeopleCraft',
        sector: 'HRTech',
        fundingStage: 'Series A',
        city: 'Gurugram',
        state: 'Haryana',
        foundingYear: 2021,
        founders: 'Sonia Narang, Raghav Bahl',
        businessModel: 'Employee experience and attrition prediction for high-growth companies',
        revenueModel: 'Per-employee SaaS subscription and analytics services',
        description: 'Measures engagement, manager risk, attrition predictors, and action plans for HR teams.',
        partnerName: 'Darwinbox Marketplace',
        dealType: 'Pilot',
        marketTrend: 70,
        competitorScore: 53,
        impactScore: 7.8,
        valuationCr: 96,
        fundingCr: 10.5,
        employeeCount: 84,
        riskScore: 37,
        cac: 3400,
        ltv: 21800,
        burnRateCr: 0.66,
        runway: 15.2,
        churnRate: 2.3,
        customerCount: 9800,
        monthlyRevenueCr: 2.45
    },
    {
        id: 47,
        name: 'ContractIQ',
        sector: 'LegalTech',
        fundingStage: 'Series A',
        city: 'Delhi',
        state: 'Delhi',
        foundingYear: 2020,
        founders: 'Vedant Suri, Priya Nanda',
        businessModel: 'AI-assisted contract lifecycle management for enterprise procurement',
        revenueModel: 'Enterprise subscription and clause-library add-ons',
        description: 'Supports contract drafting, approval routing, clause risk scoring, and renewal reminders.',
        partnerName: 'NASSCOM Legal Innovation Forum',
        dealType: 'Pilot',
        marketTrend: 74,
        competitorScore: 52,
        impactScore: 8,
        valuationCr: 112,
        fundingCr: 11.8,
        employeeCount: 88,
        riskScore: 35,
        cac: 5800,
        ltv: 35400,
        burnRateCr: 0.72,
        runway: 16,
        churnRate: 1.9,
        customerCount: 760,
        monthlyRevenueCr: 2.65
    },
    {
        id: 48,
        name: 'RentNest',
        sector: 'Proptech',
        fundingStage: 'Seed',
        city: 'Pune',
        state: 'Maharashtra',
        foundingYear: 2023,
        founders: 'Aditi Kulkarni, Yusuf Khan',
        businessModel: 'Rental discovery and managed deposit workflow for students and young professionals',
        revenueModel: 'Listing subscription, tenant service fee, and insurance commission',
        description: 'Simplifies verified rentals, deposits, move-in checks, and tenant support for college towns.',
        partnerName: 'NoBroker Partner Network',
        dealType: 'LOI',
        marketTrend: 68,
        competitorScore: 67,
        impactScore: 6.8,
        valuationCr: 32,
        fundingCr: 3.4,
        employeeCount: 29,
        riskScore: 63,
        cac: 2200,
        ltv: 7600,
        burnRateCr: 0.39,
        runway: 6.5,
        churnRate: 6.9,
        customerCount: 19200,
        monthlyRevenueCr: 0.73
    },
    {
        id: 49,
        name: 'MealMint',
        sector: 'Foodtech',
        fundingStage: 'Series A',
        city: 'Mumbai',
        state: 'Maharashtra',
        foundingYear: 2021,
        founders: 'Rohan Iyer, Shreya Shah',
        businessModel: 'Corporate meal wallet and canteen operations platform',
        revenueModel: 'Employer subscription, meal transaction fee, and vendor margin',
        description: 'Digitizes corporate meals, nutrition preferences, vendor settlement, and office canteen demand.',
        partnerName: 'Sodexo India Partner Network',
        dealType: 'Pilot',
        marketTrend: 71,
        competitorScore: 58,
        impactScore: 7.5,
        valuationCr: 86,
        fundingCr: 8.9,
        employeeCount: 78,
        riskScore: 43,
        cac: 2600,
        ltv: 13400,
        burnRateCr: 0.6,
        runway: 12.6,
        churnRate: 3.7,
        customerCount: 36000,
        monthlyRevenueCr: 2.25
    },
    {
        id: 50,
        name: 'RenderRush',
        sector: 'MediaTech',
        fundingStage: 'Seed',
        city: 'Hyderabad',
        state: 'Telangana',
        foundingYear: 2023,
        founders: 'Tara Nair, Zubin Khan',
        businessModel: 'AI-assisted short video production workflow for brands and agencies',
        revenueModel: 'Creative seat subscription, render credits, and agency workspace fees',
        description: 'Helps marketing teams generate scripts, edits, captions, and multi-platform video variants.',
        partnerName: 'T-Hub Media Lab',
        dealType: 'LOI',
        marketTrend: 78,
        competitorScore: 65,
        impactScore: 7.6,
        valuationCr: 46,
        fundingCr: 4.7,
        employeeCount: 37,
        riskScore: 51,
        cac: 1700,
        ltv: 9400,
        burnRateCr: 0.43,
        runway: 9.1,
        churnRate: 5.2,
        customerCount: 12600,
        monthlyRevenueCr: 1.02
    }
];

additionalStartupBlueprints.forEach((startup) => {
    const valuation = croreToInr(startup.valuationCr);
    const totalFunding = croreToInr(startup.fundingCr);
    const burnRate = croreToInr(startup.burnRateCr);
    const latestRevenue = croreToInr(startup.monthlyRevenueCr);

    startupDetailsById[startup.id] = {
        id: startup.id,
        name: startup.name,
        sector: startup.sector,
        fundingStage: startup.fundingStage,
        city: startup.city,
        state: startup.state,
        foundedYear: startup.foundingYear,
        founders: startup.founders,
        businessModel: startup.businessModel,
        revenueModel: startup.revenueModel,
        description: startup.description,
        partnerName: startup.partnerName,
        dealType: startup.dealType,
        marketTrend: startup.marketTrend,
        competitorScore: startup.competitorScore,
        impactScore: startup.impactScore,
        valuation,
        employeeCount: startup.employeeCount,
        totalFunding,
        riskScore: startup.riskScore,
        riskLevel: riskLevelFromScore(startup.riskScore),
        cac: startup.cac,
        ltv: startup.ltv,
        burnRate,
        runway: startup.runway,
        churnRate: startup.churnRate,
        customerCount: startup.customerCount,
        latestRevenue,
        history: []
    };
});

Object.values(startupDetailsById).forEach((startup) => {
    startup.history = buildRevenueHistory(startup);
});

const startups = Object.values(startupDetailsById);
const startupHistory = Object.fromEntries(startups.map((startup) => [startup.id, startup.history]));
const sectors = [...new Set(startups.map((startup) => startup.sector))].sort();

const riskDistribution = ['Low', 'Medium', 'High'].map((riskLevel) => ({
    label: riskLevel,
    count: startups.filter((startup) => startup.riskLevel === riskLevel).length
}));

const sectorGroups = groupBy(startups, 'sector');
const stageGroups = groupBy(startups, 'fundingStage');
const totalFundingInr = startups.reduce((sum, startup) => sum + startup.totalFunding, 0);
const averageRisk = average(startups.map((startup) => startup.riskScore));

const sectorGrowth = sectors.map((sector) => ({
    label: sector,
    value: round(average(sectorGroups[sector].map((startup) => startup.marketTrend)))
}));

const stageFunding = Object.entries(stageGroups)
    .map(([stage, stageStartups]) => ({
        label: stage,
        value: round(stageStartups.reduce((sum, startup) => sum + startup.totalFunding, 0) / 10000000)
    }))
    .sort((a, b) => b.value - a.value);

const sectorRisk = sectors.map((sector) => ({
    label: sector,
    value: round(average(sectorGroups[sector].map((startup) => startup.riskScore)))
}));

const recommendationItems = startups
    .map((startup) => {
        const ltvCacRatio = startup.ltv / startup.cac;
        const decisionScore = Math.min(9.6, Math.max(3.2,
            (ltvCacRatio * 0.78) +
            (startup.runway * 0.14) +
            ((100 - startup.riskScore) * 0.035) +
            (startup.marketTrend * 0.018)
        ));
        const signal = decisionScore >= 8
            ? 'INVEST'
            : decisionScore >= 6.4
                ? 'WATCH'
                : 'AVOID';

        return {
            startupId: startup.id,
            name: startup.name,
            sector: startup.sector,
            fundingStage: startup.fundingStage,
            decisionScore: round(decisionScore),
            signal,
            riskScore: startup.riskScore,
            ltvCacRatio: round(ltvCacRatio),
            reason: buildRecommendationReason(startup, ltvCacRatio, signal)
        };
    })
    .sort((a, b) => b.decisionScore - a.decisionScore)
    .slice(0, 8)
    .map((startup, index) => ({ ...startup, rank: index + 1 }));

const radarSectors = sectors
    .map((sector) => {
        const entries = sectorGroups[sector];
        const funding = entries.reduce((sum, startup) => sum + startup.totalFunding, 0);
        return { sector, entries, funding };
    })
    .sort((a, b) => b.funding - a.funding)
    .slice(0, 6);

const maxSectorFunding = Math.max(...radarSectors.map((entry) => entry.funding), 1);

export const fallbackData = {
    dashboard: {
        summary: {
            totalStartups: startups.length,
            totalFundingInr,
            avgROI: 31.6,
            riskLevel: averageRisk < 35 ? 'Low' : averageRisk < 65 ? 'Medium' : 'High'
        },
        sectorGrowth: {
            labels: sectorGrowth.map((entry) => entry.label),
            data: sectorGrowth.map((entry) => entry.value)
        },
        investmentTrends: {
            labels: ['Jan 2025', 'Mar 2025', 'May 2025', 'Jul 2025', 'Sep 2025', 'Nov 2025', 'Jan 2026', 'Mar 2026', 'Apr 2026'],
            data: [21, 18, 31, 26, 42, 36, 48, 54, 61]
        },
        stageFunding: {
            labels: stageFunding.map((entry) => entry.label),
            data: stageFunding.map((entry) => entry.value)
        },
        riskDistribution: {
            labels: riskDistribution.map((entry) => entry.label),
            data: riskDistribution.map((entry) => entry.count)
        },
        topStartups: recommendationItems.slice(0, 5)
    },
    sectors,
    startups: startups.map((startup) => ({
        id: startup.id,
        name: startup.name,
        sector: startup.sector,
        fundingStage: startup.fundingStage,
        city: startup.city,
        state: startup.state,
        valuation: startup.valuation,
        totalFunding: startup.totalFunding,
        riskScore: startup.riskScore,
        riskLevel: startup.riskLevel,
        runway: startup.runway,
        ltvCacRatio: round(startup.ltv / startup.cac)
    })),
    startupDetailsById,
    startupHistory,
    recommendationItems,
    analytics: {
        scatter: {
            points: startups.map((startup) => ({
                label: startup.name,
                x: startup.cac,
                y: startup.ltv
            }))
        },
        burnRunway: {
            labels: startups.map((startup) => startup.name),
            burnRateLakhs: startups.map((startup) => round(startup.burnRate / 100000)),
            runwayMonths: startups.map((startup) => startup.runway)
        },
        radar: {
            labels: [
                'Growth',
                'Risk Buffer',
                'Funding Strength',
                'Partner Impact',
                'Competition Headroom'
            ],
            datasets: radarSectors.map((entry, index) => ({
                label: entry.sector,
                data: [
                    round(average(entry.entries.map((startup) => startup.marketTrend))),
                    round(100 - average(entry.entries.map((startup) => startup.riskScore))),
                    round((entry.funding / maxSectorFunding) * 100),
                    round(average(entry.entries.map((startup) => startup.impactScore)) * 10),
                    round(100 - average(entry.entries.map((startup) => startup.competitorScore)))
                ],
                borderColor: palette[index % palette.length].borderColor,
                backgroundColor: palette[index % palette.length].backgroundColor
            }))
        },
        fundingByStage: {
            labels: stageFunding.map((entry) => entry.label),
            data: stageFunding.map((entry) => entry.value)
        },
        riskBySector: {
            labels: sectorRisk.map((entry) => entry.label),
            data: sectorRisk.map((entry) => entry.value)
        },
        valuationFunding: {
            points: startups.map((startup) => ({
                label: startup.name,
                x: round(startup.totalFunding / 10000000),
                y: round(startup.valuation / 10000000)
            }))
        },
        churnBySector: {
            labels: sectors,
            data: sectors.map((sector) => round(average(sectorGroups[sector].map((startup) => startup.churnRate))))
        }
    },
    investmentRoiById: {
        1: 210,
        2: 167.3,
        3: 60,
        4: 280,
        5: 233.33,
        6: 150,
        7: 10,
        8: 13.33,
        9: -100.8,
        10: -116.67,
        11: -40,
        12: -54.55,
        13: 229.41,
        14: 252.78
    }
};

function groupBy(items, key) {
    return items.reduce((groups, item) => {
        const groupKey = item[key];
        groups[groupKey] = groups[groupKey] || [];
        groups[groupKey].push(item);
        return groups;
    }, {});
}

function average(values) {
    if (!values.length) {
        return 0;
    }

    return values.reduce((sum, value) => sum + Number(value || 0), 0) / values.length;
}

function round(value) {
    return Number(Number(value || 0).toFixed(2));
}

function croreToInr(value) {
    return Math.round(Number(value || 0) * 10000000);
}

function riskLevelFromScore(score) {
    const numericScore = Number(score || 0);

    if (numericScore < 35) {
        return 'Low';
    }

    if (numericScore < 65) {
        return 'Medium';
    }

    return 'High';
}

function buildRevenueHistory(startup) {
    const latestRevenue = Number(
        startup.latestRevenue ||
        startup.monthlyRevenue ||
        startup.history?.[startup.history.length - 1] ||
        0
    );

    if (!latestRevenue) {
        return monthLabels.map(() => 0);
    }

    const stageStart = {
        'Pre-Seed': 0.31,
        Seed: 0.43,
        'Series A': 0.58,
        'Series B': 0.69,
        'Series C': 0.76
    }[startup.fundingStage] || 0.52;
    const sectorProgress = {
        'AI/ML': [0, 0.13, 0.39, 0.54, 0.82, 1],
        Agritech: [0, 0.08, 0.29, 0.38, 0.65, 1],
        Biotech: [0, 0.04, 0.13, 0.36, 0.54, 1],
        ClimateTech: [0, 0.09, 0.31, 0.44, 0.73, 1],
        Cybersecurity: [0, 0.22, 0.45, 0.53, 0.79, 1],
        Dronetech: [0, 0.16, 0.28, 0.48, 0.66, 1],
        Ecommerce: [0, 0.24, 0.32, 0.50, 0.68, 1],
        Edtech: [0, 0.11, 0.28, 0.47, 0.74, 1],
        Energy: [0, 0.07, 0.24, 0.52, 0.66, 1],
        Fintech: [0, 0.17, 0.36, 0.56, 0.79, 1],
        Foodtech: [0, 0.19, 0.25, 0.51, 0.70, 1],
        Gaming: [0, 0.31, 0.26, 0.58, 0.71, 1],
        Healthtech: [0, 0.08, 0.23, 0.48, 0.69, 1],
        HRTech: [0, 0.16, 0.35, 0.49, 0.75, 1],
        Insurtech: [0, 0.14, 0.33, 0.51, 0.76, 1],
        LegalTech: [0, 0.12, 0.30, 0.54, 0.77, 1],
        Logistics: [0, 0.18, 0.30, 0.50, 0.65, 1],
        MediaTech: [0, 0.27, 0.35, 0.44, 0.78, 1],
        Mobility: [0, 0.10, 0.26, 0.45, 0.72, 1],
        Proptech: [0, 0.13, 0.22, 0.42, 0.71, 1],
        Robotics: [0, 0.05, 0.24, 0.33, 0.64, 1],
        SaaS: [0, 0.18, 0.38, 0.59, 0.80, 1],
        SpaceTech: [0, 0.03, 0.18, 0.41, 0.57, 1]
    }[startup.sector] || [0, 0.15, 0.33, 0.52, 0.75, 1];
    const bumpProfiles = [
        [0, 0.00, 0.01, -0.01, 0.00, 0],
        [0, 0.04, -0.03, 0.01, -0.01, 0],
        [0, -0.02, 0.05, -0.04, 0.03, 0],
        [0, 0.01, -0.01, 0.05, -0.03, 0],
        [0, -0.03, 0.02, 0.03, 0.01, 0]
    ];
    const growthLift = clamp(
        ((Number(startup.marketTrend || 65) - 65) * 0.002) +
        ((Number(startup.runway || 8) - 8) * 0.01) -
        (Number(startup.churnRate || 4) * 0.006) +
        ((60 - Number(startup.riskScore || 50)) * 0.0015),
        -0.11,
        0.13
    );
    const startRatio = clamp(stageStart - growthLift, 0.24, 0.84);
    const bumpScale = Number(startup.riskScore || 50) >= 65 || Number(startup.churnRate || 0) >= 6
        ? 0.10
        : Number(startup.riskScore || 50) >= 50
            ? 0.065
            : 0.035;
    const bumps = bumpProfiles[Number(startup.id || 0) % bumpProfiles.length];

    return sectorProgress.map((progress, index) => {
        const ratio = index === sectorProgress.length - 1
            ? 1
            : clamp(startRatio + ((1 - startRatio) * progress) + (bumps[index] * bumpScale), 0.18, 1.02);

        return Math.max(0, Math.round(latestRevenue * ratio));
    });
}

function clamp(value, min, max) {
    return Math.min(max, Math.max(min, Number(value || 0)));
}

function buildRecommendationReason(startup, ltvCacRatio, signal) {
    if (signal === 'INVEST') {
        return `${startup.sector} traction is strong: ${ltvCacRatio.toFixed(1)}x LTV/CAC, ${startup.runway.toFixed(1)} months runway, and ${startup.partnerName} ${startup.dealType}.`;
    }

    if (signal === 'WATCH') {
        return `Promising market signal (${startup.marketTrend}/100), but risk score ${startup.riskScore.toFixed(0)} and churn ${startup.churnRate.toFixed(1)}% need monitoring.`;
    }

    return `High-risk profile: short runway, heavier churn, or capital-intensive execution before the next round.`;
}
